# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8ragaHwEMMyWD11oPMHL5-VNbOxMpyS
"""

!pip install streamlit pandas plotly

# Commented out IPython magic to ensure Python compatibility.
# # mbti.py
# %%writefile mbti.py
# 
# def mbti_quiz():
#     """
#     This is a placeholder function for the MBTI quiz.
#     Replace this with your actual implementation.
#     It should return the determined MBTI type (e.g., "ISTJ").
#     """
#     # Example placeholder logic:
#     # In a real application, you would implement a quiz
#     # and determine the MBTI type based on user answers.
#     print("Running a placeholder MBTI quiz...")
#     return "INFJ" # Example return value
# 
# def suggest_career(mbti_type, skills, major):
#     """
#     This is a placeholder function to suggest careers based on MBTI, skills, and major.
#     Replace this with your actual implementation.
#     It should return a list of suggested careers.
#     """
#     # Example placeholder logic:
#     print(f"Suggesting careers for MBTI: {mbti_type}, Skills: {skills}, Major: {major}")
#     # In a real application, you would use these inputs
#     # to find relevant career suggestions.
#     suggestions = [
#         f"Placeholder Career 1 for {mbti_type}",
#         f"Placeholder Career 2 for {major}",
#         f"Placeholder Career 3 for {', '.join(skills)}"
#     ]
#     return suggestions

# Commented out IPython magic to ensure Python compatibility.
# # app.py
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# from mbti import mbti_quiz, suggest_career
# 
# # Load dữ liệu đã làm sạch
# @st.cache_data
# def load_data():
#     df = pd.read_csv("data/Cleaned data.csv")
#     df = df.dropna(subset=['Industry', 'Location.1', 'Min Salary', 'Max Salary'])
#     return df
# 
# df = load_data()
# 
# st.set_page_config(page_title="CareerMap", layout="wide")
# st.title("🎯 CareerMap – Nền tảng hướng nghiệp cá nhân hóa")
# 
# # MBTI Test
# st.header("🧠 Trắc nghiệm MBTI đơn giản")
# # Note: In a real Streamlit app, you would likely use st.session_state
# # to store the MBTI type after the quiz is completed.
# # For now, this placeholder function is called directly.
# mbti_type = mbti_quiz()
# 
# # Nhập kỹ năng và ngành học
# st.header("🛠️ Kỹ năng và ngành học")
# skills = st.multiselect("Bạn có những kỹ năng nào?", ["Phân tích dữ liệu", "Lập trình", "Giao tiếp", "Thiết kế", "Quản lý dự án"])
# major = st.selectbox("Ngành bạn đang học là gì?", ["Kinh tế", "Công nghệ thông tin", "Truyền thông", "Kỹ thuật", "Du lịch"])
# 
# # Gợi ý nghề nghiệp
# # Ensure mbti_type is not None or empty before showing the button
# if mbti_type and st.button("🎯 Xem gợi ý nghề nghiệp"):
#     suggestions = suggest_career(mbti_type, skills, major)
#     st.subheader("🔍 Nghề nghiệp phù hợp với bạn:")
#     for job in suggestions:
#         st.markdown(f"- {job}")
# 
# # Trực quan hóa dữ liệu
# st.header("📊 Phân tích xu hướng thị trường")
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     avg_salary_industry = df.groupby("Industry")["Min Salary"].mean().reset_index()
#     fig1 = px.bar(avg_salary_industry, x="Industry", y="Min Salary", title="💼 Lương trung bình theo ngành")
#     st.plotly_chart(fig1, use_container_width=True)
# 
# with col2:
#     avg_salary_location = df.groupby("Location.1")["Min Salary"].mean().reset_index()
#     fig2 = px.bar(avg_salary_location, x="Location.1", y="Min Salary", title="🌍 Lương theo địa điểm")
#     st.plotly_chart(fig2, use_container_width=True)
# 
# # Lương theo kinh nghiệm
# st.subheader("📈 Lương trung bình theo kinh nghiệm")
# # Handle potential errors if 'EXP' column is not found or extraction fails
# try:
#     # Ensure the column exists and apply the extraction
#     if 'EXP' in df.columns:
#         df["EXP"] = df["EXP"].astype(str).str.extract(r'(\d)').dropna().astype(int)
#         # Filter out rows where EXP could not be converted to int after dropna
#         df_exp_filtered = df.dropna(subset=["EXP"])
#         if not df_exp_filtered.empty:
#             avg_exp = df_exp_filtered.groupby("EXP")["Min Salary"].mean().reset_index()
#             fig3 = px.line(avg_exp, x="EXP", y="Min Salary", markers=True, title="📈 Lương theo số năm kinh nghiệm")
#             st.plotly_chart(fig3, use_container_width=True)
#         else:
#             st.warning("Không có dữ liệu kinh nghiệm hợp lệ để hiển thị biểu đồ.")
#     else:
#          st.warning("Cột 'EXP' không tồn tại trong dữ liệu.")
# 
# except Exception as e:
#     st.error(f"Đã xảy ra lỗi khi xử lý dữ liệu kinh nghiệm: {e}")
# 
# 
# st.caption("Nguồn dữ liệu: TopCV, VietnamWorks – xử lý bởi nhóm CareerMap")

# Commented out IPython magic to ensure Python compatibility.
# # app.py
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# from mbti import mbti_quiz, suggest_career
# # import os # No longer needed
# 
# # Load dữ liệu đã làm sạch
# @st.cache_data
# def load_data():
#     # Construct the full path using the current working directory
#     # Make sure the 'data' folder is in the same directory as app.py
#     # file_path = os.path.join(os.path.dirname(__file__), "data", "Cleaned data.csv") # This caused the error
#     # Assuming 'data' is a subdirectory of the current working directory
#     file_path = "data/Cleaned data.csv"
# 
#     # Check if the file exists before trying to read it
#     # Using relative path, so check directly
#     try:
#         df = pd.read_csv(file_path)
#         df = df.dropna(subset=['Industry', 'Location.1', 'Min Salary', 'Max Salary'])
#         return df
#     except FileNotFoundError:
#         st.error(f"Lỗi: Không tìm thấy tệp dữ liệu tại đường dẫn: {file_path}. Đảm bảo thư mục 'data' và tệp 'Cleaned data.csv' tồn tại ở vị trí tương đối.")
#         # Return empty DataFrame to prevent further errors
#         return pd.DataFrame()
# 
# 
# df = load_data()
# 
# st.set_page_config(page_title="CareerMap", layout="wide")
# st.title("🎯 CareerMap – Nền tảng hướng nghiệp cá nhân hóa")
# 
# # MBTI Test
# st.header("🧠 Trắc nghiệm MBTI đơn giản")
# mbti_type = mbti_quiz()
# 
# # Nhập kỹ năng và ngành học
# st.header("🛠️ Kỹ năng và ngành học")
# skills = st.multiselect("Bạn có những kỹ năng nào?", ["Phân tích dữ liệu", "Lập trình", "Giao tiếp", "Thiết kế", "Quản lý dự án"])
# major = st.selectbox("Ngành bạn đang học là gì?", ["Kinh tế", "Công nghệ thông tin", "Truyền thông", "Kỹ thuật", "Du lịch"])
# 
# # Gợi ý nghề nghiệp
# # Add a check if df is empty from load_data error
# if mbti_type and st.button("🎯 Xem gợi ý nghề nghiệp"):
#     suggestions = suggest_career(mbti_type, skills, major)
#     st.subheader("🔍 Nghề nghiệp phù hợp với bạn:")
#     for job in suggestions:
#         st.markdown(f"- {job}")
# 
# # Trực quan hóa dữ liệu
# st.header("📊 Phân tích xu hướng thị trường")
# 
# # Add a check to ensure df is not empty before plotting
# if not df.empty:
#     col1, col2 = st.columns(2)
# 
#     with col1:
#         avg_salary_industry = df.groupby("Industry")["Min Salary"].mean().reset_index()
#         fig1 = px.bar(avg_salary_industry, x="Industry", y="Min Salary", title="💼 Lương trung bình theo ngành")
#         st.plotly_chart(fig1, use_container_width=True)
# 
#     with col2:
#         avg_salary_location = df.groupby("Location.1")["Min Salary"].mean().reset_index()
#         fig2 = px.bar(avg_salary_location, x="Location.1", y="Min Salary", title="🌍 Lương theo địa điểm")
#         st.plotly_chart(fig2, use_container_width=True)
# 
#     # Lương theo kinh nghiệm
#     st.subheader("📈 Lương trung bình theo kinh nghiệm")
#     # Handle potential errors if 'EXP' column is not found or extraction fails
#     try:
#         # Ensure the column exists and apply the extraction
#         if 'EXP' in df.columns:
#             # Ensure data in 'EXP' is string before applying str methods
#             # Add error handling for conversion if some values aren't convertible
#             df["EXP"] = df["EXP"].astype(str).str.extract(r'(\d)').dropna()
#             # Convert to int only after dropping NaNs
#             df["EXP"] = df["EXP"].astype(int)
# 
#             # Filter out rows where EXP could not be converted to int after dropna (though astype(int) would raise error first)
#             # A better approach might be to use .loc for assignment after filtering
#             df_exp_filtered = df.dropna(subset=["EXP"])
# 
#             if not df_exp_filtered.empty:
#                 avg_exp = df_exp_filtered.groupby("EXP")["Min Salary"].mean().reset_index()
#                 fig3 = px.line(avg_exp, x="EXP", y="Min Salary", markers=True, title="📈 Lương theo số năm kinh nghiệm")
#                 st.plotly_chart(fig3, use_container_width=True)
#             else:
#                 st.warning("Không có dữ liệu kinh nghiệm hợp lệ để hiển thị biểu đồ.")
#         else:
#              st.warning("Cột 'EXP' không tồn tại trong dữ liệu.")
# 
#     except Exception as e:
#         st.error(f"Đã xảy ra lỗi khi xử lý dữ liệu kinh nghiệm: {e}")
# else:
#     st.warning("Không thể tải dữ liệu để hiển thị biểu đồ.")
# 
# 
# st.caption("Nguồn dữ liệu: TopCV, VietnamWorks – xử lý bởi nhóm CareerMap")